// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxuaqftpjagtvhtwqdym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4dWFxZnRwamFndHZodHdxZHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzE3MDMsImV4cCI6MjA2NDEwNzcwM30.ats7jpVTYGVhRBHCK_lyLMlfSvGIWuc1KTf-T9eccak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);