// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lztbbprbklhaidhqfajn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dGJicHJia2xoYWlkaHFmYWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Mjg1MzQsImV4cCI6MjA2NDEwNDUzNH0.iYT0279l8X30DSE2GQCp9lvQuXFCzGOtI1l46xStxX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);